[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cookiecutter-python-package-demo"
authors = [{name = "Steven van de Graaf", email = "steven@vandegraaf.xyz"}]
readme = "README.md"
license = {file = "LICENSE"}
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]
requires-python = "~=3.7"
dependencies = []
dynamic = ["version", "description"]

[project.optional-dependencies]
dev = [
    "autoflake",
    "black",
    "flake8",
    "isort",
    "mypy",
    "pre-commit",
    "pyupgrade",
]
docs = [
    "furo",
    "myst-parser",
    "sphinx",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinxext-opengraph",
]
tests = [
    "pytest"
]

[project.urls]
Documentation = "https://cookiecutter-python-package-demo.readthedocs.io/en/stable/"
Changelog = "https://cookiecutter-python-package-demo.readthedocs.io/en/stable/changelog.html"
"Source code" = "https://github.com/sgraaf/cookiecutter-python-package-demo"
Issues = "https://github.com/sgraaf/cookiecutter-python-package-demo/issues"

[tool.isort]
profile = "black"
