name: Publish Python Package

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install the latest version of uv with caching enabled
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run nox "release-to-pypi" session
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uvx nox --session release-to-pypi
